## es_1
dato n creare un array 1d

    [0,1,0,1,0,1.....] 
    
per n volte

In [2]:
import numpy as np

In [9]:
n= 5
array = np.ones(n)
array[0:n:2]=0
array

array([0., 1., 0., 1., 0.])

## es_2
matrice n colonne e n righe

In [52]:
array = np.zeros((n, n), dtype=np.int8)
print(array)
array[::2, 1::2] = 1
array[1::2, ::2] = 0
array

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


array([[0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0],
       [0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0],
       [0, 1, 0, 1, 0]], dtype=int8)

## es_3
trovare massimi e minimi locali e globali 
dato 

    v=np.array([1,2,3,1,-2,4,3,1,2])

In [3]:
v=np.array([1,2,3,1,-2,4,3,1,2])

In [4]:
np.max(v)

4

In [6]:
array_dx = np.roll(v, 1)
array_dx

array([ 2,  1,  2,  3,  1, -2,  4,  3,  1])

In [7]:
array_sx = np.roll(v, -1)
array_sx

array([ 2,  3,  1, -2,  4,  3,  1,  2,  1])

In [8]:
(v > array_sx) & (v > array_dx)

array([False, False,  True, False, False,  True, False, False,  True])

In [9]:
v1 = v[(v > array_sx) & (v > array_dx)] #vettorizzazione
v1

array([3, 4, 2])

In [39]:
v[(v < array_sx) & (v < array_dx)]

array([ 1, -2,  1])