In [2]:
import numpy as np

In [ ]:
%%timeit
quadrati=[]
for i in range(1000000):
    quadrati.append(i**2)

In [ ]:
quadrati

In [ ]:
%%timeit
quadrati = np.arange(0, 1000000) **2

## Creare gli array unidimensionali

In [4]:
array_di_zeri = np.zeros(10)
array_di_zeri.dtype

dtype('float64')

In [6]:
array_di_zeri_int=np.zeros(10, dtype=np.int8)
array_di_zeri_int

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [7]:
array_di_uni=np.ones(10)
array_di_uni

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [9]:
array_di_cinque=np.ones(10)*5 #ogni elemento viene moltiplicato--> BROADCAST
array_di_cinque

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [10]:
array_da_lista_numeri=np.array([1, 2, 3, 1000])
array_da_lista_numeri

array([   1,    2,    3, 1000])

In [11]:
array_da_lista_numeri=np.array([1, 2, 3, 1000, "c"])
array_da_lista_numeri

array(['1', '2', '3', '1000', 'c'], dtype='<U11')

In [13]:
np.random.uniform(3,5, 10) #ritorna un numero float tra n1 e n2, n3 è il numero di volte di estrazione: dimensione array

array([3.0752521 , 4.08852266, 3.92355179, 3.83631081, 3.10950301,
       3.85496126, 4.18809359, 3.55431324, 3.77137219, 3.51163437])

In [21]:
int_casuali = np.random.randint(1, 7, 10) #sorteggiati tra 1 incluso e 7 escuso
int_casuali

array([4, 1, 6, 1, 6, 2, 5, 1, 6, 2])

In [29]:
alice = np.random.randint(1,7,10)
bob = np.random.randint(1,7,10)

In [31]:
alice > bob

array([False, False, False, False, False,  True, False,  True,  True,
        True])

In [32]:
print(f"alice batte bob {np.count_nonzero(alice>bob)} volte")

alice batte bob 4 volte


In [34]:
vittorie_alice = alice > bob
vittorie_alice.dtype

dtype('bool')

In [3]:
array_di_interi=np.arange(4,10)
array_di_interi

array([4, 5, 6, 7, 8, 9])

In [5]:
quadrati = np.arange(1, 11)**2
quadrati

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [10]:
array1=np.arange(1,5)
array1.shape #ti da quanti valori e le dimensioni (in questo caso 1)
array1.dtype

dtype('int32')

In [9]:
array2=np.ones(4)
array2.dtype

dtype('float64')

In [14]:
somma=array1+array2
somma

array([2., 3., 4., 5.])

In [15]:
somma.dtype

dtype('float64')

## creazione array 1d
array di zeri:
    
    np.zeros()

array di uni:
    
    np.ones()
    
array da liste:
    
    np.array()
    
array di interi crescenti:
    
    np.arange()
    
array pseudocasuali:

    np.random.randint()
    np.random.uniform()

# Array pseudocasuali

In [16]:
np.random.randint(1,3,10)

array([1, 2, 1, 2, 2, 2, 1, 2, 1, 2])

In [17]:
np.random.uniform(0,1,10)

array([0.29208823, 0.64585185, 0.18135981, 0.50948289, 0.83356059,
       0.69660646, 0.15795747, 0.8618208 , 0.07956433, 0.3125469 ])

In [38]:
altezze = np.random.normal(175,4,10000)
altezze

array([178.4605771 , 170.3378981 , 177.55017757, ..., 169.11853115,
       173.53558974, 175.11697713])

In [39]:
np.mean(altezze)

175.0003565206321

In [40]:
np.std(altezze)

4.024422901891568

## indicizzazione per booleani
### Una delle funzioni più potenti di nunpy

In [41]:
lanci_dadi = np.random.randint(1,7,10)
lanci_dadi

array([4, 4, 5, 1, 3, 2, 1, 1, 2, 6])

quali sono i lanci in cui il valore del dado era > 3?

In [42]:
lanci_gt_3 =lanci_dadi >3
lanci_gt_3

array([ True,  True,  True, False, False, False, False, False, False,
        True])

In [43]:
lanci_dadi[lanci_gt_3] #indicizzo array con array di booleanee

array([4, 4, 5, 6])

In [44]:
nomi = np.array(["Alice", "Bob", "Trudy"])
voti = np.array([7, 9, 2])

quali alunni sono sufficienti?

In [45]:
nomi[voti>6]

array(['Alice', 'Bob'], dtype='<U5')

quali punteggi ha fatto alice quando ha vinto?

In [46]:
alice = np.random.randint(1,7,10)
bob = np.random.randint(1,7,10)
alice[alice>bob]

array([5, 4, 2, 4, 4])

### Array bidimensionali
es:
- un'immagine in scale di grigi
- un'immagine RGB a colori costituita da 3 array 2d
- un'immagine RGBA a colori è costituita da 4 array 2d
- i dati in forma di tabella

In [7]:
matrice_di_zeri = np.zeros((3,6)) #con tupla si crea una matrice
matrice_di_zeri

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [8]:
matrice_di_zeri.shape

(3, 6)

In [9]:
array1d_di_zeri=np.zeros(7)
array1d_di_zeri

array([0., 0., 0., 0., 0., 0., 0.])

In [10]:
array1d_di_zeri.shape

(7,)

In [13]:
np.ones((10,8), dtype=np.int8)

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]], dtype=int8)

In [15]:
np.array([[1,2,3], [23,12,22]]) #devono essere rettangolari, se una lunga 4 e una 3 le vede come LISTE

array([[ 1,  2,  3],
       [23, 12, 22]])

In [16]:
np.array([[1,2,3], [23,12,'ciao']]).dtype

dtype('<U11')

In [17]:
np.random.randint(1, 7, (10,2))

array([[6, 3],
       [2, 1],
       [2, 5],
       [5, 1],
       [3, 6],
       [6, 3],
       [1, 4],
       [5, 2],
       [4, 6],
       [6, 1]])

In [21]:
array3D = np.random.uniform(0, 1, (3,3,2))
array3D

array([[[0.91434357, 0.086467  ],
        [0.63632601, 0.20857841],
        [0.62098906, 0.32073411]],

       [[0.30550464, 0.8832814 ],
        [0.71904161, 0.18755068],
        [0.93771215, 0.81137955]],

       [[0.45655556, 0.97729857],
        [0.24397838, 0.50595551],
        [0.73639013, 0.0782105 ]]])

### Operazioni matematiche di aggregazione
Per esempio:
- somma
- massimo / minimo
- media
- dev. standard
- somma cumulata

In [23]:
#somma
array = np.arange(1, 101)
np.sum(array)

5050

In [27]:
#massimo / minimo
array = np.random.uniform(0,1,10)
np.max(array)

array([0.91193539, 0.22360979, 0.97706444, 0.0789556 , 0.63812919,
       0.35981597, 0.61691892, 0.08155508, 0.44720172, 0.05725906])

In [28]:
#dev. standard
np.std(array)

0.32254356661308187

In [30]:
array_di_uni = np.ones(10)
array_di_uni

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [32]:
np.cumsum(array_di_uni) #es. terzo elemento = somma dei primi tre

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [35]:
prezzo_apple = 178
variazioni = np.array([8, 3, -20, 6]) #aumento o diminuzione delle azioni della apple (giorno 1= +8)

In [37]:
prezzo_apple + np.cumsum(variazioni) #godo

array([186, 189, 169, 175])

### Cambiare forma agli array

In [41]:
array_1d = np.arange(1, 13)
array_1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [44]:
array_1d.reshape((6,2))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [48]:
array_1d.reshape((3, -1)) #-1 vuol dire complizazione automatica (in questo caso 4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

#### Esercizio
dato n intero generare l'array 2d in questo modo:

    [[1, 2, 3, ..., n],
     [1, 2, 3, ..., n],
     ...
     ...
     [1, 2, 3, ..., n]]
con n righe

In [62]:
n = 4
array_1d = np.arange(1, n*n+1)
array2d = (array_1d%n).reshape((n,-1))
array2d = 1 + np.roll(array2d, 1)
array2d

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [63]:
array2d.reshape(-1)

array([1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4])

In [65]:
array2d.flatten()

array([1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4])

### Slicing

In [67]:
array1d = np.arange(1,11)
array1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [68]:
array1d[3]

4

In [69]:
array1d[3:8]

array([4, 5, 6, 7, 8])

In [70]:
array1d[-1]

10

In [71]:
array1d[-2]

9

In [72]:
array1d[1:-1]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
array1d[1:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [74]:
array1d[3:8:2]

array([4, 6, 8])

In [83]:
np.random.seed(10)
array2d = np.random.uniform(0, 1, (3,3))
array2d

array([[0.77132064, 0.02075195, 0.63364823],
       [0.74880388, 0.49850701, 0.22479665],
       [0.19806286, 0.76053071, 0.16911084]])

In [76]:
array2d[0, 0]

0.771320643266746

In [77]:
array2d[1, 2]

0.22479664553084766

In [78]:
array2d[1:]

array([[0.74880388, 0.49850701, 0.22479665],
       [0.19806286, 0.76053071, 0.16911084]])

In [79]:
array2d[:, 1:]

array([[0.02075195, 0.63364823],
       [0.49850701, 0.22479665],
       [0.76053071, 0.16911084]])

In [80]:
array2d[1:, 1:]

array([[0.49850701, 0.22479665],
       [0.76053071, 0.16911084]])

In [84]:
array2d[1:, 1:] = 0
array2d

array([[0.77132064, 0.02075195, 0.63364823],
       [0.74880388, 0.        , 0.        ],
       [0.19806286, 0.        , 0.        ]])